import { Button } from '@nextui-org/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Component = () => <Button>Click me</Button>;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>Trang chủ</main>
    </>
  );
};

export default Home;
